import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-articuloshack',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './articuloshack.component.html',
  styleUrl: './articuloshack.component.css'
})
export class ArticuloshackComponent {
  ngOnInit(): void {
    console.log(`id recibido ${this.id}`);
  }
  @Input()
  id:string='';
  articulos= [
    {id:'1',nombre:'Hacking etico',descripcion:'En este mundo globalizado, los accesos al mundo de la información son la ventana que ayuda a la visibilidad de productos ofrecidos en el comercio electrónico. Pero el estado frágil de los mismos, mediante los data leaks, ha hecho necesario que los reguladores de las entidades financieras obliguen a efectuar pruebas continuas en los servidores con el fin de prevenir incidentes. En ese marco, los equipos de respuesta ante emergencias informáticas (CSIRT, por sus siglas en inglés) generan reportes semanales que conllevan información relevante sobre exploits circulantes en el cibermundo, siendo los bug bounty quienes, alimentados por los programas de recompensas de entidades como Facebook, Google o PayPal, atribuyen reconocimiento en un hall of fame a quienes colaboran para descubrir fallos de seguridad. Pero en este mundo no todo es tan ideal. Para un proceso de hacking ético se requiere cumplir con pasos y normativas, siendo los mismos establecidos en los procesos de convocatorias de contrataciones estatales. La transparencia en el acceso de información hace que estas licitaciones ayuden a reclutar empresas para efectuar estas labores, no sin antes firmar los contratos de confidencialidad correspondientes con el fin de que ninguna información, a raíz de los procesos de auditoría informática, sea accesible para terceros. Lamentablemente, los servicios de hacking ético son mal solicitados. Se trata de solicitudes de acceso de información de transferencia de documentos de empleados a externos, espionaje industrial, accesos remotos no autorizados, sabotaje informático, archivos ocultos o porque la entidad sufrió un ataque de ransomware. Pero todos estos motivos corresponden a análisis informático forense, dado que el hacking ético se efectúa de forma preventiva, no post mortem.',imagen:'https://th.bing.com/th/id/OIP.TD_cTLcpfA9WGcRW3uMu_AHaD4?w=336&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7'},
    {id:'2',nombre:'Legislacion de seguridad europea ',descripcion:'Cada vez son más necesarias respuestas avanzadas y coordinadas en el ámbito de la ciberseguridad, a medida que los ciberataques aumentan en número, escala y consecuencias, lo que afecta gravemente a nuestra seguridad. Todos las partes interesadas de la UE deben estar listas para responder colectivamente e intercambiar información pertinente sobre la base de la «necesidad de comunicar», y no solo de la «necesidad de conocer». La unidad informática conjunta propuesta hoy, anunciada por la presidenta Ursula von der Leyen en sus orientaciones políticas, tiene por objeto reunir los recursos y la experiencia de que disponen la UE y sus Estados miembros para prevenir, disuadir y responder eficazmente en materia de cibercrisis y ciberincidentes masivos. Las partes interesadas en la ciberseguridad, incluidas las del mundo civil, policial, diplomático y de ciberdefensa, y los socios del sector privado suelen trabajar demasiado a menudo por separado. Junto con la unidad informática conjunta, contarán con una plataforma virtual y física de cooperación: las instituciones, órganos y organismos pertinentes de la UE, en colaboración con los Estados miembros, crearán gradualmente una plataforma europea de solidaridad y asistencia para luchar contra los ciberataques a gran escala. La Recomendación sobre la creación de la unidad informática conjunta es un paso importante hacia la culminación del marco europeo de gestión de crisis de ciberseguridad. Se trata de un resultado concreto de la Estrategia de Ciberseguridad de la UE y de la Estrategia de la Unión Europea de la Seguridad que contribuye a una economía y una sociedad digitales seguras. En el marco de este paquete, la Comisión informa hoy acerca de los progresos registrados en los últimos meses en relación con la Estrategia de la Unión de la Seguridad. Además, la Comisión y el Alto Representante de la Unión para Asuntos Exteriores y Política de Seguridad han presentado el primer informe de ejecución de la Estrategia de Ciberseguridad, solicitado por el Consejo Europeo, y han publicado a la vez el quinto informe de situación sobre la ejecución del marco común de 2016 de lucha contra las amenazas híbridas y la Comunicación conjunta de 2018 «Aumentar la resiliencia y desarrollar las capacidades para hacer frente a las amenazas híbridas». Por último, la Comisión ha adoptado la Decisión por la que se establece en Bruselas la Agencia de la Unión Europea para la Ciberseguridad (ENISA), de conformidad con el Reglamento de ciberseguridad.',imagen:'https://www.secureit.es/wp-content/uploads/2018/11/Real-Decreto-Directiva-NIS.png'},
    {id:'3',nombre:'¿Como evitar que te hackeen la cuenta? ',descripcion:'Desde que tenemos teléfonos móviles, desde que los correos electrónicos son nuestra llave de acceso a servicios, plataformas y productos de toda clase en la red, proteger nuestros datos se ha vuelto vital. Sobre todo, con la creciente amenaza de unos hackers cada vez más inteligentes y cada vez con más herramientas.Si quieres evitar que accedan a tus cuentas de usuario y a tus datos personales, debes empezar a tomar una serie de medidas de seguridad imprescindibles. No es necesario moverse con total cautela en internet y con miedo a todo, pero sí que es aconsejable establecer ciertas pautas en tu rutina de navegación habitual. Puede que lo que te expliquemos a continuación haga un poco más engorroso el uso de tu teléfono, tu tablet o tu PC, pero son recomendaciones hechas por y para tu seguridad. Si las pones en práctica, tu privacidad quedará totalmente protegida.Tendemos a utilizar la misma contraseña para diferentes plataformas porque siempre es más fácil de memorizar. El gran problema de esto es que, si se vulnera en un sitio, se vulnera en todos. Un peligroso efecto dominó que pone totalmente en riesgo tu seguridad y privacidad. Por eso, usa claves distintas para diferentes webs y servicios. ¿Tienes miedo de no recordarlas? No te preocupes, puedes usar soluciones como este gestor de contraseñas, ideales para no perderte.La verificación en dos pasos es un protocolo de seguridad que, además de exigir la introducción de una clave de usuario, también obliga a validar el acceso a través de otra vía. Puede ser mediante un mensaje de texto corto a un móvil, mediante una clave a un correo o incluso a través de la introducción de un PIN o la pulsación en un botón en una app de verificación. Sea como fuere, aunque ralentiza el proceso de login, es la vía más segura en los tiempos que corren.',imagen:'https://www.movilzona.es/app/uploads-movilzona.es/2021/12/seguridad-movil-android-930x487.jpg'},
    {id:'4',nombre:'¿Que es el phising?',descripcion:'Imagina el desconcierto al pagar con tu tarjeta y enterarte que tu dinero ha sido robado. Esta situación la viven diariamente muchas personas en el mundo. Dan clic en un link “inocente” y toda su información es robada.El phishing es un método que los ciber delincuentes utilizan para engañar y conseguir que se revele información personal, como contraseñas, datos de tarjetas de crédito o de la seguridad social y números de cuentas bancarias, entre otros. Obtienen esta información mediante el envío de correos electrónicos fraudulentos o dirigiendo a la persona a un sitio web falso.El ataque funciona así: el correo electrónico tiene contenido hasta cierto punto convincente o amenazante, que genera cierta duda en el usuario y lo hace abrir un archivo o llenar un formulario.El engaño que más se presenta en la actualidad es por correo electrónico. Sin embargo, la obtención de la información también puede ser a través de las redes sociales. Por lo que debemos ser cuidadosos sobre lo que publicamos.En el primer caso, el usuario en realidad no tiene la certeza de que algo puede ocurrirle a su equipo de cómputo sólo con entrar a un enlace. Cree que no pasa nada cuando en realidad es posible que sí, ya que al dar un clic sin pensar  en su computadora se podría estar instalando un malwere, es decir, un programa malicioso que le ocasionaría daños.Un usuario también puede ser víctima de phishing por temor cuando le llegan mensajes de advertencia en los que lee frases amenazantes. Por miedo a que la amenaza se cumpla el usuario da clic en el enlace y en ese momento es susceptible de que su información personal sea robada.',imagen:'https://th.bing.com/th/id/OIP.UYLoTkpfkTKERZRBlx3PoAHaE8?rs=1&pid=ImgDetMain'},
  ];
}
