import { Injectable } from '@angular/core';
import { Inmueble } from '../_modelo/Inmueble';

@Injectable({
  providedIn: 'root'
})
export class InmuebleService {
  inmuebles:Inmueble[]=[
    {id:1,nombre:'Casa con vistas al mar',descripcion:' Hermosa villa rústica estilo hacienda en una zona residencial muy tranquila de Artola, Alta. A pocos pasos de la reserva natural, dunas y playa de Artola, playa y puertos de Cabopino, restaurantes y supermercados. La casa es de una sola planta y consta de 3 dormitorios y 2 baños. Su distribución garantiza la privacidad debido a que el dormitorio principal y el baño están separados de los dormitorios y el baño de invitados por el salón y el comedor. La casa es privada y está aislada por un muro perimetral. A la propiedad se accede desde el norte desde la calle a través de un portón que da paso a un patio con acceso a un garaje doble y una entrada cubierta a la casa. La entrada de la casa da paso a una cocina totalmente equipada y a un amplio comedor. La casa se abre hacia el sur con una sala de estar que da acceso a una terraza cubierta, un jardín y la zona de la piscina que está enclavada por un jardín tropical maduro y exuberante. El jardín cuenta con varios árboles frutales. La casa también tiene una terraza en la azotea de 20 m2 donde se puede ver el mar y la puesta de sol sobre la bahía de Marbella y la montaña de La Concha. Una villa cómoda y auténtica que podrás disfrutar de inmediato. Visitas preferiblemente por la tarde o los fines de semana.',imagen:'https://th.bing.com/th/id/R.6e30e750e42bcdb1657d8795fc444cc3?rik=mxSyht%2fOYl92oQ&riu=http%3a%2f%2farquitecturaideal.com%2fwp-content%2fuploads%2f2015%2f01%2fcasa-vistas-oceano-4.jpg&ehk=j6EzsTZXyJBWH8P9keqdAJxWkn%2frZFPhBw4qg3BhsOs%3d&risl=&pid=ImgRaw&r=0'},
    {id:2,nombre:'Cabaña en la montaña ',descripcion:'Abandonen sus horarios de oficina, sus traslados diarios, el ajetreo de la vida en la ciudad y el estrés, para visitar esta impresionante cabaña en los bosques de la Columbia Británica. Solo necesitan ropa cómoda, sus botas de montaña y un buen libro, porque esta cabaña tiene todo lo demás.La cabaña incluye dos hermosos porches, una cocina renovada a la perfección y una estufa de madera. Esta cabaña es el oasis de tranquilidad con el que han soñado, y lo mejor de todo es que puede ser suyo. De modo que no hay ninguna necesidad de alquilar una cabaña en el bosque, pueden sencillamente comprar la Bella Coola Health Resort. Disfruten del recorrido, enamórense y disfruten de todo lo que tiene para ofrecer.Esta acogedora cabaña encaja a la perfección con sus alrededores. El alto tejado acaba en pico, como las cumbres montañosas que lo rodean, y el exterior de madera es rústico y agradable como los bosques que franquean el porche.Normalmente, uno tiende a concentrarse en los bellos interiores de una casa. Sin embargo, lo que atrae a la gente a este lugar es la naturaleza salvaje. Esta cabaña aprovecha su entorno al máximo y para sacar partido a las hermosas vistas tiene dos porches.',imagen:'https://static.mansionglobal.com/production/media/article-images/40aa54ac9ed0f893fcc70ce849a0972a/large_BN-LR207_1221SK_GR_20151211154405.jpg'},
    {id:4,nombre:'Mansion norte ',descripcion:'Esta villa es muy famosa en Italia y en muchas partes del mundo. Conocida como Villa Sola Cabiati y situada a orillas del lago de Como, en la región de Lombardía, es la antigua residencia de verano de los Duques de Serbelloni. Inspirada en el barroco, el edificio central empezó a construirse en el siglo XVI, aunque posteriormente se amplió. Desde el siglo XVIII tiene el aspecto actual. Destacan sus balcones de mármol, su espectacular entrada con una escalera doble y la gran puerta de entrada de hierro forjado. En su interior destacan los frisos y la colección privada de arte. Tiene seis habitaciones y seis baños, además de piscina. La villa tiene dos pisos y tiene capacidad para alojar hasta 12 personas, aunque según la web Luxury Retreats, el precio del alojamiento arranca en unos 7.800 dólares (unos 7.000 euros) con decoración barroca y recargada, donde destacan los cuadros, los espejos, lámparas grandes y papel pintado en las paredes. El color dorado es uno de los que tiene más presencia.',imagen:'https://th.bing.com/th/id/R.f16ccb8d978b115d2eea0fb2f4579122?rik=BBV9Fn033Wn0Ug&pid=ImgRaw&r=0'},
    {id:5,nombre:'Mansion sur ',descripcion:'Esta vez volamos hasta bel air, en la ciudad de los ángeles, california, donde se encuentra esta mega-mansión de más de 3.700 m2 y nada menos que 28 dormitorios. Destaca la piscina exterior y la zona de relax desde la que ver el mar.Esta impresionante mansión, conocida como hilltop compound, ha sido diseñada por el estudio de arquitectura landry design group en 2010. Esta mansión se compone de la casa principal, de una casa para invitados, otra para los empleados y otra para el entretenimiento.La vivienda cuenta con más de 3.700 m2 y otros más de 6.000 m2 de terreno. La piscina exterior tiene dos alturas y anejo  se encuentra la zona de relax con vistas a la ciudad de los ángeles en california (eeuu). Además, de los 28 dormitorios, cuenta con una zona de spa',imagen:'https://st3.idealista.com/news/archivos/styles/fullwidth_xl_2x/public/2012-02/casa-ensueno-bel-air4_0.jpg?VersionId=BuO8RtfoFYJtha3UN64HCkj3.j06d.dl&itok=7ggVb2N_'},
    {id:6,nombre:'Casa pueblo ',descripcion:'Lo mejor de esta casa es que podrás disfrutar de la playa que se encuentra a unos escasos 100 metros de distancia.La vivienda está dividida en dos plantas que constan de salón, comedor, cocina independiente, un aseo, patio interior con jardín y garaje en la planta baja. En la planta superior hay tres dormitorios y un cuarto de baño.Casa construida en 1800 y completamente reformada. En su interior consta de cuatro dormitorios, uno de ellos con vestidor, cuatro cuartos de baño, salón con chimenea, cocina, comedor, galería con porche y terraza con acceso al jardín.',imagen:'https://www.fotocasa.es/blog/wp-content/uploads/2019/10/6.casas_-768x431.jpg'}
  ];
  articulos:Inmueble[]=[
  {id:1,nombre:'Hacking etico',descripcion:'En este mundo globalizado, los accesos al mundo de la información son la ventana que ayuda a la visibilidad de productos ofrecidos en el comercio electrónico. Pero el estado frágil de los mismos, mediante los data leaks, ha hecho necesario que los reguladores de las entidades financieras obliguen a efectuar pruebas continuas en los servidores con el fin de prevenir incidentes. En ese marco, los equipos de respuesta ante emergencias informáticas (CSIRT, por sus siglas en inglés) generan reportes semanales que conllevan información relevante sobre exploits circulantes en el cibermundo, siendo los bug bounty quienes, alimentados por los programas de recompensas de entidades como Facebook, Google o PayPal, atribuyen reconocimiento en un hall of fame a quienes colaboran para descubrir fallos de seguridad. Pero en este mundo no todo es tan ideal. Para un proceso de hacking ético se requiere cumplir con pasos y normativas, siendo los mismos establecidos en los procesos de convocatorias de contrataciones estatales. La transparencia en el acceso de información hace que estas licitaciones ayuden a reclutar empresas para efectuar estas labores, no sin antes firmar los contratos de confidencialidad correspondientes con el fin de que ninguna información, a raíz de los procesos de auditoría informática, sea accesible para terceros. Lamentablemente, los servicios de hacking ético son mal solicitados. Se trata de solicitudes de acceso de información de transferencia de documentos de empleados a externos, espionaje industrial, accesos remotos no autorizados, sabotaje informático, archivos ocultos o porque la entidad sufrió un ataque de ransomware. Pero todos estos motivos corresponden a análisis informático forense, dado que el hacking ético se efectúa de forma preventiva, no post mortem.',imagen:'https://th.bing.com/th/id/OIP.TD_cTLcpfA9WGcRW3uMu_AHaD4?w=336&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7'},
  {id:2,nombre:'Legislacion de seguridad europea ',descripcion:'Cada vez son más necesarias respuestas avanzadas y coordinadas en el ámbito de la ciberseguridad, a medida que los ciberataques aumentan en número, escala y consecuencias, lo que afecta gravemente a nuestra seguridad. Todos las partes interesadas de la UE deben estar listas para responder colectivamente e intercambiar información pertinente sobre la base de la «necesidad de comunicar», y no solo de la «necesidad de conocer». La unidad informática conjunta propuesta hoy, anunciada por la presidenta Ursula von der Leyen en sus orientaciones políticas, tiene por objeto reunir los recursos y la experiencia de que disponen la UE y sus Estados miembros para prevenir, disuadir y responder eficazmente en materia de cibercrisis y ciberincidentes masivos. Las partes interesadas en la ciberseguridad, incluidas las del mundo civil, policial, diplomático y de ciberdefensa, y los socios del sector privado suelen trabajar demasiado a menudo por separado. Junto con la unidad informática conjunta, contarán con una plataforma virtual y física de cooperación: las instituciones, órganos y organismos pertinentes de la UE, en colaboración con los Estados miembros, crearán gradualmente una plataforma europea de solidaridad y asistencia para luchar contra los ciberataques a gran escala. La Recomendación sobre la creación de la unidad informática conjunta es un paso importante hacia la culminación del marco europeo de gestión de crisis de ciberseguridad. Se trata de un resultado concreto de la Estrategia de Ciberseguridad de la UE y de la Estrategia de la Unión Europea de la Seguridad que contribuye a una economía y una sociedad digitales seguras. En el marco de este paquete, la Comisión informa hoy acerca de los progresos registrados en los últimos meses en relación con la Estrategia de la Unión de la Seguridad. Además, la Comisión y el Alto Representante de la Unión para Asuntos Exteriores y Política de Seguridad han presentado el primer informe de ejecución de la Estrategia de Ciberseguridad, solicitado por el Consejo Europeo, y han publicado a la vez el quinto informe de situación sobre la ejecución del marco común de 2016 de lucha contra las amenazas híbridas y la Comunicación conjunta de 2018 «Aumentar la resiliencia y desarrollar las capacidades para hacer frente a las amenazas híbridas». Por último, la Comisión ha adoptado la Decisión por la que se establece en Bruselas la Agencia de la Unión Europea para la Ciberseguridad (ENISA), de conformidad con el Reglamento de ciberseguridad.',imagen:'https://www.secureit.es/wp-content/uploads/2018/11/Real-Decreto-Directiva-NIS.png'},
  {id:3,nombre:'¿Como evitar que te hackeen la cuenta? ',descripcion:'Desde que tenemos teléfonos móviles, desde que los correos electrónicos son nuestra llave de acceso a servicios, plataformas y productos de toda clase en la red, proteger nuestros datos se ha vuelto vital. Sobre todo, con la creciente amenaza de unos hackers cada vez más inteligentes y cada vez con más herramientas.Si quieres evitar que accedan a tus cuentas de usuario y a tus datos personales, debes empezar a tomar una serie de medidas de seguridad imprescindibles. No es necesario moverse con total cautela en internet y con miedo a todo, pero sí que es aconsejable establecer ciertas pautas en tu rutina de navegación habitual. Puede que lo que te expliquemos a continuación haga un poco más engorroso el uso de tu teléfono, tu tablet o tu PC, pero son recomendaciones hechas por y para tu seguridad. Si las pones en práctica, tu privacidad quedará totalmente protegida.Tendemos a utilizar la misma contraseña para diferentes plataformas porque siempre es más fácil de memorizar. El gran problema de esto es que, si se vulnera en un sitio, se vulnera en todos. Un peligroso efecto dominó que pone totalmente en riesgo tu seguridad y privacidad. Por eso, usa claves distintas para diferentes webs y servicios. ¿Tienes miedo de no recordarlas? No te preocupes, puedes usar soluciones como este gestor de contraseñas, ideales para no perderte.La verificación en dos pasos es un protocolo de seguridad que, además de exigir la introducción de una clave de usuario, también obliga a validar el acceso a través de otra vía. Puede ser mediante un mensaje de texto corto a un móvil, mediante una clave a un correo o incluso a través de la introducción de un PIN o la pulsación en un botón en una app de verificación. Sea como fuere, aunque ralentiza el proceso de login, es la vía más segura en los tiempos que corren.',imagen:'https://www.movilzona.es/app/uploads-movilzona.es/2021/12/seguridad-movil-android-930x487.jpg'},
  {id:4,nombre:'¿Que es el phising?',descripcion:'Imagina el desconcierto al pagar con tu tarjeta y enterarte que tu dinero ha sido robado. Esta situación la viven diariamente muchas personas en el mundo. Dan clic en un link “inocente” y toda su información es robada.El phishing es un método que los ciber delincuentes utilizan para engañar y conseguir que se revele información personal, como contraseñas, datos de tarjetas de crédito o de la seguridad social y números de cuentas bancarias, entre otros. Obtienen esta información mediante el envío de correos electrónicos fraudulentos o dirigiendo a la persona a un sitio web falso.El ataque funciona así: el correo electrónico tiene contenido hasta cierto punto convincente o amenazante, que genera cierta duda en el usuario y lo hace abrir un archivo o llenar un formulario.El engaño que más se presenta en la actualidad es por correo electrónico. Sin embargo, la obtención de la información también puede ser a través de las redes sociales. Por lo que debemos ser cuidadosos sobre lo que publicamos.En el primer caso, el usuario en realidad no tiene la certeza de que algo puede ocurrirle a su equipo de cómputo sólo con entrar a un enlace. Cree que no pasa nada cuando en realidad es posible que sí, ya que al dar un clic sin pensar  en su computadora se podría estar instalando un malwere, es decir, un programa malicioso que le ocasionaría daños.Un usuario también puede ser víctima de phishing por temor cuando le llegan mensajes de advertencia en los que lee frases amenazantes. Por miedo a que la amenaza se cumpla el usuario da clic en el enlace y en ese momento es susceptible de que su información personal sea robada.',imagen:'https://th.bing.com/th/id/OIP.UYLoTkpfkTKERZRBlx3PoAHaE8?rs=1&pid=ImgDetMain'},
];
inmueblesC: Inmueble[]=[
    {id:1,nombre:'Casa con vistas al mar',descripcion:'El océano puede ser contemplado prácticamente desde todos los rincones de la vivienda y el uso de grandes ventanas y paredes de cristal ayudan a conseguir este objetivo. Una casa de ensueño donde más de uno querría pasar toda su vida',imagen:'https://th.bing.com/th/id/R.6e30e750e42bcdb1657d8795fc444cc3?rik=mxSyht%2fOYl92oQ&riu=http%3a%2f%2farquitecturaideal.com%2fwp-content%2fuploads%2f2015%2f01%2fcasa-vistas-oceano-4.jpg&ehk=j6EzsTZXyJBWH8P9keqdAJxWkn%2frZFPhBw4qg3BhsOs%3d&risl=&pid=ImgRaw&r=0'},
    {id:2,nombre:'Cabaña en la montaña ',descripcion:'Abandonen sus horarios de oficina, sus traslados diarios, el ajetreo de la vida en la ciudad y el estrés, para visitar esta impresionante cabaña en los bosques de la Columbia Británica.',imagen:'https://static.mansionglobal.com/production/media/article-images/40aa54ac9ed0f893fcc70ce849a0972a/large_BN-LR207_1221SK_GR_20151211154405.jpg'},
    {id:3,nombre:'Piso en madrid ',descripcion:'En la mejor zona del barrio de Almagro presentamos en exclusiva este maravilloso piso reformado. Se trata de una vivienda en una ubicación privilegiada, completamente exterior salvo la cocina, con dos habitaciones y tres baños y plaza de garaje con acceso directo incluida en el precio.',imagen:'https://www.john-taylor.es/alquiler-piso-madrid-ori100-L1036MA-80978810.jpg?datetime=2020-09-13'},
    {id:4,nombre:'Mansion norte ',descripcion:'Esta villa es muy famosa en Italia y en muchas partes del mundo. Conocida como Villa Sola Cabiati y situada a orillas del lago de Como, en la región de Lombardía, es la antigua residencia de verano de los Duques de Serbelloni',imagen:'https://th.bing.com/th/id/R.f16ccb8d978b115d2eea0fb2f4579122?rik=BBV9Fn033Wn0Ug&pid=ImgRaw&r=0'},
    {id:5,nombre:'Mansion sur ',descripcion:'Esta vez volamos hasta bel air, en la ciudad de los ángeles, california, donde se encuentra esta mega-mansión de más de 3.700 m2 y nada menos que 28 dormitorios. Destaca la piscina exterior y la zona de relax desde la que ver el mar',imagen:'https://st3.idealista.com/news/archivos/styles/fullwidth_xl_2x/public/2012-02/casa-ensueno-bel-air4_0.jpg?VersionId=BuO8RtfoFYJtha3UN64HCkj3.j06d.dl&itok=7ggVb2N_'},
    {id:6,nombre:'Casa pueblo ',descripcion:'Lo mejor de esta casa es que podrás disfrutar de la playa que se encuentra a unos escasos 100 metros de distancia.La vivienda está dividida en dos plantas que constan de salón, comedor, cocina independiente, un aseo, patio interior con jardín y garaje en la planta baja. En la planta superior hay tres dormitorios y un cuarto de baño.',imagen:'https://www.fotocasa.es/blog/wp-content/uploads/2019/10/6.casas_-768x431.jpg'}
];
articulosC:Inmueble[]=[
    {id:1,nombre:'Hacking etico',descripcion:' Los procesos que se efectúan con el fin de verificar la integridad de una entidad gubernamental o privada y detectar las vulnerabilidades potenciales',imagen:'https://th.bing.com/th/id/OIP.TD_cTLcpfA9WGcRW3uMu_AHaD4?w=336&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7'},
    {id:2,nombre:'Legislacion de seguridad europea ',descripcion:'La Comisión ha presentado una visión para construir una nueva unidad informática conjunta para hacer frente al creciente número de ciberincidentes graves que afectan a todos.',imagen:'https://www.secureit.es/wp-content/uploads/2018/11/Real-Decreto-Directiva-NIS.png'},
    {id:3,nombre:'¿Como evitar que te hackeen la cuenta? ',descripcion:'La seguridad online se ha convertido en una asignatura obligatoria para cualquier ciudadano de a pie',imagen:'https://www.movilzona.es/app/uploads-movilzona.es/2021/12/seguridad-movil-android-930x487.jpg'},
    {id:4,nombre:'¿Que es el phising?',descripcion:'El phishing es un método que los ciber delincuentes utilizan para engañar y conseguir que se revele información personal,',imagen:'https://th.bing.com/th/id/OIP.UYLoTkpfkTKERZRBlx3PoAHaE8?rs=1&pid=ImgDetMain'},
  
]
  public obtenerInmuebles(): Inmueble[]{
    return this.inmuebles;
  }
  public obtenerArticulos(): Inmueble[]{
    return this.articulos;
  }
  public obtenerInmueblesC(): Inmueble[]{
    return this.inmueblesC;
  }
  public obtenerArticulosC(): Inmueble[]{
    return this.articulosC;
  }
}
