import { Component, Input, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-articulo',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './articulo.component.html',
  styleUrl: './articulo.component.css'
})
export class ArticuloComponent implements OnInit {
  ngOnInit(): void {
    console.log(`id recibido ${this.id}`);
  }
  @Input()
  id:string='';

  articulos= [
    {id:'1',nombre:'Casa con vistas al mar',descripcion:' Hermosa villa rústica estilo hacienda en una zona residencial muy tranquila de Artola, Alta. A pocos pasos de la reserva natural, dunas y playa de Artola, playa y puertos de Cabopino, restaurantes y supermercados. La casa es de una sola planta y consta de 3 dormitorios y 2 baños. Su distribución garantiza la privacidad debido a que el dormitorio principal y el baño están separados de los dormitorios y el baño de invitados por el salón y el comedor. La casa es privada y está aislada por un muro perimetral. A la propiedad se accede desde el norte desde la calle a través de un portón que da paso a un patio con acceso a un garaje doble y una entrada cubierta a la casa. La entrada de la casa da paso a una cocina totalmente equipada y a un amplio comedor. La casa se abre hacia el sur con una sala de estar que da acceso a una terraza cubierta, un jardín y la zona de la piscina que está enclavada por un jardín tropical maduro y exuberante. El jardín cuenta con varios árboles frutales. La casa también tiene una terraza en la azotea de 20 m2 donde se puede ver el mar y la puesta de sol sobre la bahía de Marbella y la montaña de La Concha. Una villa cómoda y auténtica que podrás disfrutar de inmediato. Visitas preferiblemente por la tarde o los fines de semana.',imagen:'https://th.bing.com/th/id/R.6e30e750e42bcdb1657d8795fc444cc3?rik=mxSyht%2fOYl92oQ&riu=http%3a%2f%2farquitecturaideal.com%2fwp-content%2fuploads%2f2015%2f01%2fcasa-vistas-oceano-4.jpg&ehk=j6EzsTZXyJBWH8P9keqdAJxWkn%2frZFPhBw4qg3BhsOs%3d&risl=&pid=ImgRaw&r=0'},
    {id:'2',nombre:'Cabaña en la montaña ',descripcion:'Abandonen sus horarios de oficina, sus traslados diarios, el ajetreo de la vida en la ciudad y el estrés, para visitar esta impresionante cabaña en los bosques de la Columbia Británica. Solo necesitan ropa cómoda, sus botas de montaña y un buen libro, porque esta cabaña tiene todo lo demás.La cabaña incluye dos hermosos porches, una cocina renovada a la perfección y una estufa de madera. Esta cabaña es el oasis de tranquilidad con el que han soñado, y lo mejor de todo es que puede ser suyo. De modo que no hay ninguna necesidad de alquilar una cabaña en el bosque, pueden sencillamente comprar la Bella Coola Health Resort. Disfruten del recorrido, enamórense y disfruten de todo lo que tiene para ofrecer.Esta acogedora cabaña encaja a la perfección con sus alrededores. El alto tejado acaba en pico, como las cumbres montañosas que lo rodean, y el exterior de madera es rústico y agradable como los bosques que franquean el porche.Normalmente, uno tiende a concentrarse en los bellos interiores de una casa. Sin embargo, lo que atrae a la gente a este lugar es la naturaleza salvaje. Esta cabaña aprovecha su entorno al máximo y para sacar partido a las hermosas vistas tiene dos porches.',imagen:'https://static.mansionglobal.com/production/media/article-images/40aa54ac9ed0f893fcc70ce849a0972a/large_BN-LR207_1221SK_GR_20151211154405.jpg'},
    {id:'3',nombre:'Piso en madrid ',descripcion:'En la mejor zona del barrio de Almagro presentamos en exclusiva este maravilloso piso reformado. Se trata de una vivienda en una ubicación privilegiada, completamente exterior salvo la cocina, con dos habitaciones y tres baños y plaza de garaje con acceso directo incluida en el precio.El salón en chaflán es el corazón de la casa, ofreciendo una fantástica luminosidad y sensación de espacio, además de múltiples posibilidades de distribución del mobiliario. En el verano, la altura de los árboles nos ofrecerá sombra, frescor y tranquilidad. En el invierno, los edificios vecinos nos recordarán constantemente dónde estamos ubicados. La habitación principal cuenta con baño en suite, armarios empotrados y vestidor. La segunda habitación dispone de armarios empotrados y su propio baño completo, todo ello reformado y exterior, sin duda un lujo difícil de encontrar. La cocina nos ofrece todas las comodidades, así como cuarto de lavado y plancha, un baño de servicio completo y su propia entrada de servicio.La tranquilidad y elitismo de la zona, la proximidad a la mejor zona del Barrio de Salamanca, la luz, el lujo de plaza de garaje en la finca o la seguridad de la propia calle convierten a esta vivienda en una oportunidad única.',imagen:'https://www.john-taylor.es/alquiler-piso-madrid-ori100-L1036MA-80978810.jpg?datetime=2020-09-13'},
    {id:'4',nombre:'Mansion norte ',descripcion:'Esta villa es muy famosa en Italia y en muchas partes del mundo. Conocida como Villa Sola Cabiati y situada a orillas del lago de Como, en la región de Lombardía, es la antigua residencia de verano de los Duques de Serbelloni. Inspirada en el barroco, el edificio central empezó a construirse en el siglo XVI, aunque posteriormente se amplió. Desde el siglo XVIII tiene el aspecto actual. Destacan sus balcones de mármol, su espectacular entrada con una escalera doble y la gran puerta de entrada de hierro forjado. En su interior destacan los frisos y la colección privada de arte. Tiene seis habitaciones y seis baños, además de piscina. La villa tiene dos pisos y tiene capacidad para alojar hasta 12 personas, aunque según la web Luxury Retreats, el precio del alojamiento arranca en unos 7.800 dólares (unos 7.000 euros) con decoración barroca y recargada, donde destacan los cuadros, los espejos, lámparas grandes y papel pintado en las paredes. El color dorado es uno de los que tiene más presencia.',imagen:'https://th.bing.com/th/id/R.f16ccb8d978b115d2eea0fb2f4579122?rik=BBV9Fn033Wn0Ug&pid=ImgRaw&r=0'},
    {id:'5',nombre:'Mansion sur ',descripcion:'Esta vez volamos hasta bel air, en la ciudad de los ángeles, california, donde se encuentra esta mega-mansión de más de 3.700 m2 y nada menos que 28 dormitorios. Destaca la piscina exterior y la zona de relax desde la que ver el mar.Esta impresionante mansión, conocida como hilltop compound, ha sido diseñada por el estudio de arquitectura landry design group en 2010. Esta mansión se compone de la casa principal, de una casa para invitados, otra para los empleados y otra para el entretenimiento.La vivienda cuenta con más de 3.700 m2 y otros más de 6.000 m2 de terreno. La piscina exterior tiene dos alturas y anejo  se encuentra la zona de relax con vistas a la ciudad de los ángeles en california (eeuu). Además, de los 28 dormitorios, cuenta con una zona de spa',imagen:'https://st3.idealista.com/news/archivos/styles/fullwidth_xl_2x/public/2012-02/casa-ensueno-bel-air4_0.jpg?VersionId=BuO8RtfoFYJtha3UN64HCkj3.j06d.dl&itok=7ggVb2N_'},
    {id:'6',nombre:'Casa pueblo ',descripcion:'Lo mejor de esta casa es que podrás disfrutar de la playa que se encuentra a unos escasos 100 metros de distancia.La vivienda está dividida en dos plantas que constan de salón, comedor, cocina independiente, un aseo, patio interior con jardín y garaje en la planta baja. En la planta superior hay tres dormitorios y un cuarto de baño.Casa construida en 1800 y completamente reformada. En su interior consta de cuatro dormitorios, uno de ellos con vestidor, cuatro cuartos de baño, salón con chimenea, cocina, comedor, galería con porche y terraza con acceso al jardín.',imagen:'https://www.fotocasa.es/blog/wp-content/uploads/2019/10/6.casas_-768x431.jpg'}

  ];

}
